title: Silverashの隙间
timezone: Asia/Shanghai
baseurl: "" 
url: "" 
repository: "siiverash/siiverash.github.io"
description: "Attention Is All You Need!"
encoding: utf-8 

github:
  name: "siiverash.github.io"
  owner: "siiverash"
  is_project: false

social:
  github: "https://github.com/siiverash"
  twitter: "https://x.com/Wolfram1907" 
  pixiv: "https://www.pixiv.net/users/55937658" 
  email: "z1379523665@gmail.com" 

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
